[2023-12-11T22:22:55.415+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:35:00+00:00 [queued]>
[2023-12-11T22:22:55.473+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:35:00+00:00 [queued]>
[2023-12-11T22:22:55.478+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-11T22:22:55.609+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-12-11 00:35:00+00:00
[2023-12-11T22:22:59.415+0000] {standard_task_runner.py:57} INFO - Started process 4916 to run task
[2023-12-11T22:23:00.576+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_postgres_table', 'scheduled__2023-12-11T00:35:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpzzo40lzg']
[2023-12-11T22:23:01.581+0000] {standard_task_runner.py:85} INFO - Job 128: Subtask create_postgres_table
[2023-12-11T22:23:10.310+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_dag.create_postgres_table scheduled__2023-12-11T00:35:00+00:00 [running]> on host d5f251ea7e03
[2023-12-11T22:23:43.000+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sajal' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:35:00+00:00'
[2023-12-11T22:23:43.590+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-12-11T22:23:45.188+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:23:48.134+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11T22:23:48.866+0000] {sql.py:418} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2023-12-11T22:23:49.456+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_postgres_table, execution_date=20231211T003500, start_date=20231211T222255, end_date=20231211T222349
[2023-12-11T22:24:00.988+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-12-11T22:24:01.777+0000] {process_utils.py:131} INFO - Sending 15 to group 4916. PIDs of all processes in the group: [4916]
[2023-12-11T22:24:01.860+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 4916
[2023-12-11T22:24:03.196+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4916, status='terminated', exitcode=0, started='22:22:59') (4916) terminated with exit code 0
